seed: 3
epoch: 1000
eval_interval: 20
h_dim: 32
z_dim: 16
n_layers: 1
clip: 10
lr: 1e-2
eps: 1e-8
conv_type: GCN # SAGE
datasets: enron10 # dplb fb

hydra:
  job:
    chdir: true
  run:
    dir: ./runs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.override_dirname}
